[workspace]
resolver = "2" 

[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking_program = "8i7Z83cmwAfv4gwWooYcqaiPn3vdRNyhUjRXrx11Ydyw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pranav/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
